### ISSUE TITLE
Matplot 라이브러리를 이용하여 소속함수 그리기

### ISSUE THREAD

**Issue by minjune8506** [minjune8506/FuzzyAI#5]
Python Matploblib 이용 소속함수 그리기

- [x] 답장이 오는데 걸리는 시간 (분)
- [x] 좋아하는 사람의 집까지 걸리는 시간 (분)
- [x] 그 사람과 사귈 확률 (%)
- [x] 물음표 갯수
- [x] 만나는 횟수

**Comment by minjune8506** [comment]
**Sample**
<img width="2114" alt="스크린샷 2022-04-06 14 39 45" src="https://user-images.githubusercontent.com/42430982/161903332-6d341e47-cc2c-42da-a55f-17263a0ee576.png">

**Comment by kpeel5839** [comment]
넘흐넘흐 이뻐영

**Comment by minjune8506** [comment]
**Update**
<img width="1765" alt="스크린샷 2022-04-06 17 23 40" src="https://user-images.githubusercontent.com/42430982/161930158-58fb8aa0-1101-47c5-8aa7-b43ffb0a2bb2.png">

**Comment by minjune8506** [comment]
**Verson 1.0**
<img width="1176" alt="스크린샷 2022-04-07 19 40 23" src="https://user-images.githubusercontent.com/42430982/162181707-92aa94c5-f204-4ce3-80bb-8cdc6cd280a9.png">
